#define DATATYPE_ION 0
#define DATATYPE_IONREC 1
#define DATATYPE_LEVEL 2
#define DATATYPE_RADIATION 3
#define DATATYPE_E_COLLISION 4
#define DATATYPE_P_COLLISION 5
#define DATATYPE_SATELLITE 6
#define DATATYPE_EMISSION 7

#define IONREC_TYPE_RR 1
#define IONREC_NAME_RR "RR"
#define IONREC_TYPE_DR 2
#define IONREC_NAME_DR "DR"
#define IONREC_TYPE_CI 3
#define IONREC_NAME_CI "CI"
#define IONREC_TYPE_EA 4
#define IONREC_NAME_EA "EA"

#define HDUCLASS_ATOMIC "ATOMIC"
#define HDUCLAS1_VER "1.0.0"
#define IONREC_FITS "IONREC"
#define LEVEL_FITS "E_LEVEL"
#define RADIATION_FITS "EM_LINES"
#define COLLISION_FITS "COLL_STR"
#define SATELLITE_FITS "DR_LINES"
#define EMISSION_FITS "EM_FEATURES"

#define FITSKEY_ELEMENT  "ELEMENT"
#define FITSKEY_IONSTATE "ION_STAT"
#define FITSKEY_IONSTAT "ION_STATE"
#define FITSKEY_IONNAME  "ION_NAME"

struct FILEMAP{
  int datatype;
  int Z;
  int rmJ;
  char filename[MAXSTRLEN];
  struct FILEMAP *next;
};

